### ISSUE TITLE
스터디 간 코드 공유를 위한 필요 작업

### ISSUE THREAD

**Issue by jayn2u** [ssuperpower-developer/design-pattern-study#2]
다들 어떻게 코드를 작성할 지는 모르겠는데, 아는 vscode에서 편집해서 터미널로 작업하거나, 인텔리제이를 사용할 생각이야.
`gitignore` 신경 쓸 필요없이 그냥 올려도 괜찮아요? 협업은 아니니까 상관은 없는데, 나는 `Xcode`에서 작업할 때는 사용자 데이터 같은 건 제외하고 업로드 하거든. 한 번 이야기 나누어주었으면 좋겠어요~

**Comment by HI-JIN2** [comment]
음 생성 파일이나 지웅이가 말한 파일 같은거는 gitignore에 등록해주세요! 미관상 안 올리는게 좋을 것 같아요

**Comment by jayn2u** [comment]
형규형이 여기에 할당이 안되네? 이것도 한 번 확인해줘.

**Comment by k0000k** [comment]
형규,,,, 어디갔어...

**Comment by HI-JIN2** [comment]
그거 초대 안받아서 그럼.. 난 햇음..
